#!/bin/sh
# cvt 1360 768|grep "^[^#]"|sed -e 's/Modeline //g'|xargs xrandr --newmode
# xrandr --addmode VGA-0 1360x768_60.00
# xrandr --output VGA-0 --mode 1360x768_60.00
# xrdb -merge ~/.Xresources
exec i3
